groups:
  clinic-ops:
    chat_id: "-5366865126"
    message_thread_id: ""
reminders:
  - name: "mon"
    group: "clinic-ops"
    photo: "https://picsum.photos/seed/mon/800/500.jpg"
    text: |-
      ──────────
      Việc hôm nay:
      🏋️ Gym
      ➕ Học Toán
      📚 Ôn IELTS
      💻 Tech

      💪 Cố lên nè!
  - name: "tue"
    group: "clinic-ops"
    photo: "https://picsum.photos/seed/tue/800/500.jpg"
    text: |-
      ──────────
      Việc hôm nay:
      ✏️ Chứng sức nhận sinh lên tới SS Hữu hạn
      📖 Xem lại bài
      📚 Học IELTS
      🔤 Ôn từ vựng

      💪 Cố lên nè!
  - name: "wed"
    group: "clinic-ops"
    photo: "https://picsum.photos/seed/wed/800/500.jpg"
    text: |-
      ──────────
      Việc hôm nay:
      🏋️ Gym
      📚 Học IELTS
      💻 Tech
      🔤 Ôn từ vựng
      ➕ Toán

      💪 Cố lên nè!
  - name: "thu"
    group: "clinic-ops"
    photo: "https://picsum.photos/seed/thu/800/500.jpg"
    text: |-
      ──────────
      Việc hôm nay:
      🏋️ Gym
      📚 Học IELTS
      💻 Tech
      🔤 Ôn từ vựng
      📖 Xem lại bài

      💪 Cố lên nè!
  - name: "fri"
    group: "clinic-ops"
    photo: "https://picsum.photos/seed/fri/800/500.jpg"
    text: |-
      ──────────
      Việc hôm nay:
      🏋️ Gym
      💻 Tech

      💪 Cố lên nè!
  - name: "sat"
    group: "clinic-ops"
    photo: "https://picsum.photos/seed/sat/800/500.jpg"
    text: |-
      ──────────
      Việc hôm nay:
      😌 Ngày Hơi Lì 😄
      📚 Học IELTS
      ➕ +4 (các mục khác)

      💪 Cố lên nè!
  - name: "sun"
    group: "clinic-ops"
    photo: "https://picsum.photos/seed/sun/800/500.jpg"
    text: |-
      ──────────
      Việc hôm nay:
      🏋️ Gym
      📚 IELTS
      ➕ Toán

      💪 Cố lên nè!
